### ISSUE TITLE
Update Crete items and advisors on Celeste search

### ISSUE THREAD

**Issue by JEINX** [ProjectCeleste/celeste-search#318]
noting at the bottom of the items on Celestesearch that they are crete exclusive, or found in crete loot table.

**Comment by System-Glitch** [comment]
**Info**

```
<trait name="ArmorBldg_U001">
<trait name="ArmorPlt_UA01">
```

the ones with "A" in them belong to crete
the ones with "B" in them belong to skirmish hall

take what's after the underscore and check if it contains an A (only if it's a non-celeste item)
