### ISSUE TITLE
High Vizier's Robe minimum damage

### ISSUE THREAD

**Issue by arydenbck** [ProjectCeleste/celeste-search#817]
I have a high vizier's robe with 24.3% damage which is lower than the listed minimum damage for the item in item finder
![highviz](https://user-images.githubusercontent.com/1882414/165780704-61e33b24-6849-4ba8-b047-9ec91afa292d.png)
.

**Comment by romaniac01** [comment]
Lvl 25 can go as low as 23.4%

**Comment by romaniac01** [comment]
Not an issue

**Comment by arydenbck** [comment]
You're not understanding. The minimum damage listed on the item search needs to be updated.

**Comment by romaniac01** [comment]
Please have a look at your item. It level 25. 

Please go to the website and then you need to click on the different options available at levels at the bottom.

Then click on 25 and you will see that the average is 24.6%
With a range (5% down and 5% up on the right) getting you as low as 23.4% and up as high as 25.8%

**Comment by romaniac01** [comment]
Furthermore.  Why you have there is an item that was most likely farmed by buying lvl 25 chests from moes.

That's a very common way to find low level items.

However if you were to play a map that would be lvl 32 required and it would provide you with lvl 29 chests. Then there could be a possibility that you may indeed find a lvl 29 version of this item ( though low). This can come from either the guardian camps within the map or at the end when you complete the quest. 

But there are very few lvl 32 quests and these cannot be repeated.
